# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy ASP app to Azure Web App - senparcweixinsample

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: 'windows-latest'

    steps:
    - uses: actions/checkout@master

    - name: Set Up .NET SDK
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: |
            10.0.x
      
    - name: Restore NuGet packages
      run: dotnet restore "./Samples/All/net10-mvc/"
      
    - name: Publish to folder
      run: dotnet publish "Samples/All/net10-mvc/Senparc.Weixin.Sample.Net10.sln" --no-restore -o published

    #- name: Deploy to Azure Web App
    #  uses: azure/webapps-deploy@v2
    #  with:
    #    app-name: 'senparcweixinsamplenetcore3'
    #    slot-name: 'senparcweixinsamplenet5'
    #    publish-profile: ${{ secrets.AzureAppService_PublishProfile_3ee3a42f0a324bf7be968d8c232a8555 }}
    #    package: \published\
